### ISSUE TITLE
error in code

### ISSUE THREAD

**Issue by PhoneSix** [Jittor/PointCloudLib#11]
Hi, @MenghaoGuo , when I ran this code,
`CUDA_VISIBLE_DEVICES=0 python train_cls.py --model pointconv`
I got the following mistakes,
`Traceback (most recent call last):
  File "train_cls.py", line 155, in <module>
    train(net, optimizer, epoch, train_dataloader, args)
  File "train_cls.py", line 67, in train
    output = net(pts)
  File "/userhome/evns/jittor/lib/python3.7/site-packages/jittor/__init__.py", line 730, in __call__
    return self.execute(*args, **kw)
  File "/userhome/PointCloudLib/networks/cls/pointconv.py", line 29, in execute
    l3_xyz, l3_points = self.sa3(l2_xyz, l2_points)
  File "/userhome/evns/jittor/lib/python3.7/site-packages/jittor/__init__.py", line 730, in __call__
    return self.execute(*args, **kw)
  File "/userhome/PointCloudLib/misc/pointconv_utils.py", line 380, in execute
    new_xyz, new_points, grouped_xyz_norm, grouped_density = sample_and_group_all(xyz, points, density_scale.reshape(B, N, 1))
NameError: name 'sample_and_group_all' is not defined`
I check the code in PointCloudLib/misc/pointconv_utils.py. It seems that there is no such function as sample_and_group_all. Can you add this function in the code?

**Comment by MenghaoGuo** [comment]
Thanks for point out it, we will check and fix soon.
