### ISSUE TITLE
[bug] ModuleNotFoundError: No module named 'cpp_wrappers.cpp_neighbors.radius_neighbors'

### ISSUE THREAD

**Issue by Bailey-24** [Jittor/PointCloudLib#15]
```bash
Traceback (most recent call last):
  File "train_cls.py", line 18, in <module>
    from data_utils.kpconv_loader import KPConvLoader
  File "/home/jiahui/Desktop/ComputerGraph/pointnet/PointCloudLib/data_utils/kpconv_loader.py", line 10, in <module>
    import cpp_wrappers.cpp_neighbors.radius_neighbors as cpp_neighbors
ModuleNotFoundError: No module named 'cpp_wrappers.cpp_neighbors.radius_neighbors'
```

I fixed this by changing the `cpp_wrappers.cpp_neighbors.radius_neighbors`  to `cpp_wrappers.cpp_neighbors.neighbors`.
But I can't make sure I'm right. So, would you please check it out?

**Comment by Bailey-24** [comment]
How to visible the classification or segmentation results?

> ```shell
> Traceback (most recent call last):
>   File "train_cls.py", line 18, in <module>
>     from data_utils.kpconv_loader import KPConvLoader
>   File "/home/jiahui/Desktop/ComputerGraph/pointnet/PointCloudLib/data_utils/kpconv_loader.py", line 10, in <module>
>     import cpp_wrappers.cpp_neighbors.radius_neighbors as cpp_neighbors
> ModuleNotFoundError: No module named 'cpp_wrappers.cpp_neighbors.radius_neighbors'
> ```
> 
> I fixed this by changing the `cpp_wrappers.cpp_neighbors.radius_neighbors` to `cpp_wrappers.cpp_neighbors.neighbors`. But I can't make sure I'm right. So, would you please check it out?

It works.
And the acc is `[Epoch 299] val acc=0.8938, best=0.9032`.
But I have another question, how did I visible the classification results?
